[package]
name = "aether-backend-llvm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aether-frontend = { path = "../aether-frontend" }
aether-middle = { path = "../aether-middle" }

[lints]
workspace = true
