from __future__ import annotations

from dataclasses import dataclass

from .runtime_common import LLVMRuntimeCommon


@dataclass(frozen=True)
class LLVMStringRuntime:
    """Private one-word UTF-8 string-object runtime.

    The header spelling and helpers are compiler/runtime implementation details;
    they deliberately do not establish a stable C ABI.
    """

    enabled: bool
    parsing: bool = False
    splitting: bool = False
    codec: bool = False

    HEADER_SIZE = 24
    IMMORTAL = 1
    UTF8_VALID = 2

    def append(self, sections: list[str]) -> None:
        if not self.enabled:
            return

        declare = LLVMRuntimeCommon.declare
        declare(sections, "declare noalias ptr @malloc(i64)")
        declare(sections, "declare void @free(ptr)")
        declare(sections, "declare i32 @puts(ptr)")
        declare(sections, "declare i32 @putchar(i32)")
        declare(sections, "declare void @exit(i32) noreturn")
        declare(sections, "declare i32 @memcmp(ptr, ptr, i64)")
        declare(sections, "declare i64 @fwrite(ptr, i64, i64, ptr)")
        declare(sections, "declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)")
        declare(sections, "declare { i64, i1 } @llvm.uadd.with.overflow.i64(i64, i64)")
        declare(sections, "@stdout = external global ptr")

        sections.extend(
            [
                "%AetherStringObject = type { i64, i64, i32, i32, [0 x i8] }",
                '@.aether.string.empty = private constant { i64, i64, i32, i32, [1 x i8] } { i64 0, i64 0, i32 3, i32 0, [1 x i8] c"\\00" }, align 8',
                self._panic_data(),
                self._validate_descriptor(),
                self._accessors(),
                self._retain(),
                self._release(),
                self._equal(),
                self._concat(),
                self._trim(),
                self._compare(),
                self._print(),
                self._print_escaped(),
                self._utf8_validator(),
                self._from_utf8(),
            ]
        )
        if self.splitting:
            sections.append(self._split())
        if self.parsing or self.codec:
            declare(sections, "declare ptr @newlocale(i32, ptr, ptr)")
            declare(sections, "declare void @freelocale(ptr)")
            if self.parsing:
                declare(sections, "declare double @strtod_l(ptr, ptr, ptr)")
            if self.codec:
                declare(sections, "declare ptr @uselocale(ptr)")
                declare(sections, "declare i32 @snprintf(ptr, i64, ptr, ...)")
            sections.extend(
                [
                    '@.aether.locale.c = private unnamed_addr constant [2 x i8] c"C\\00"',
                ]
            )
        if self.parsing:
            sections.extend([self._parse_int(), self._parse_double()])
        if self.codec:
            sections.append(self._codec_helpers())

    @staticmethod
    def _codec_helpers() -> str:
        return "\n\n".join([
            '\n'.join([
                '@.aether.text.range = private unnamed_addr constant [48 x i8] c"Aether panic: invalid internal text codec range\\00"',
                '@.aether.text.int.format = private unnamed_addr constant [3 x i8] c"%d\\00"',
                '@.aether.text.double.format = private unnamed_addr constant [6 x i8] c"%.17g\\00"',
                "define private void @aether_text_range_panic() noreturn {",
                "entry:",
                "  %message = getelementptr [48 x i8], ptr @.aether.text.range, i64 0, i64 0",
                "  call i32 @puts(ptr %message)",
                "  call void @exit(i32 1)",
                "  unreachable",
                "}",
            ]),
            '\n'.join([
                "define private i32 @aether_text_byte_at(ptr %value, i32 %offset32) {",
                "entry:",
                "  call void @aether_string_validate(ptr %value)",
                "  %negative = icmp slt i32 %offset32, 0",
                "  %offset = sext i32 %offset32 to i64",
                "  %length = call i64 @aether_string_byte_length(ptr %value)",
                "  %past_end = icmp uge i64 %offset, %length",
                "  %invalid = or i1 %negative, %past_end",
                "  br i1 %invalid, label %panic, label %load",
                "load:",
                "  %data = call ptr @aether_string_data(ptr %value)",
                "  %byte_ptr = getelementptr i8, ptr %data, i64 %offset",
                "  %byte = load i8, ptr %byte_ptr",
                "  %result = zext i8 %byte to i32",
                "  ret i32 %result",
                "panic:",
                "  call void @aether_text_range_panic()",
                "  unreachable",
                "}",
            ]),
            '\n'.join([
                "define private ptr @aether_text_byte_slice(ptr %value, i32 %start32, i32 %slice_length32) {",
                "entry:",
                "  call void @aether_string_validate(ptr %value)",
                "  %negative_start = icmp slt i32 %start32, 0",
                "  %negative_length = icmp slt i32 %slice_length32, 0",
                "  %negative = or i1 %negative_start, %negative_length",
                "  %start = sext i32 %start32 to i64",
                "  %slice_length = sext i32 %slice_length32 to i64",
                "  %end_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %start, i64 %slice_length)",
                "  %end = extractvalue { i64, i1 } %end_pair, 0",
                "  %overflow = extractvalue { i64, i1 } %end_pair, 1",
                "  %length = call i64 @aether_string_byte_length(ptr %value)",
                "  %past_end = icmp ugt i64 %end, %length",
                "  %bad_sum = or i1 %overflow, %past_end",
                "  %invalid = or i1 %negative, %bad_sum",
                "  br i1 %invalid, label %panic, label %slice",
                "slice:",
                "  %data = call ptr @aether_string_data(ptr %value)",
                "  %start_ptr = getelementptr i8, ptr %data, i64 %start",
                "  %result = call ptr @aether_string_from_utf8(ptr %start_ptr, i64 %slice_length)",
                "  ret ptr %result",
                "panic:",
                "  call void @aether_text_range_panic()",
                "  unreachable",
                "}",
            ]),
            '\n'.join([
                "define private ptr @aether_text_format_int(i32 %value) {",
                "entry:",
                "  %buffer = alloca [16 x i8], align 1",
                "  %data = getelementptr [16 x i8], ptr %buffer, i64 0, i64 0",
                "  %format = getelementptr [3 x i8], ptr @.aether.text.int.format, i64 0, i64 0",
                "  %written32 = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %data, i64 16, ptr %format, i32 %value)",
                "  %written = sext i32 %written32 to i64",
                "  %result = call ptr @aether_string_from_utf8(ptr %data, i64 %written)",
                "  ret ptr %result",
                "}",
            ]),
            '\n'.join([
                "define private ptr @aether_text_format_double(double %value) {",
                "entry:",
                "  %bits = bitcast double %value to i64",
                "  %exponent = and i64 %bits, 9218868437227405312",
                "  %nonfinite = icmp eq i64 %exponent, 9218868437227405312",
                "  br i1 %nonfinite, label %panic, label %prepare",
                "prepare:",
                "  %locale_name = getelementptr [2 x i8], ptr @.aether.locale.c, i64 0, i64 0",
                "  %locale = call ptr @newlocale(i32 2, ptr %locale_name, ptr null)",
                "  %locale_failed = icmp eq ptr %locale, null",
                "  br i1 %locale_failed, label %panic, label %format_value",
                "format_value:",
                "  %previous = call ptr @uselocale(ptr %locale)",
                "  %buffer = alloca [64 x i8], align 1",
                "  %data = getelementptr [64 x i8], ptr %buffer, i64 0, i64 0",
                "  %format = getelementptr [6 x i8], ptr @.aether.text.double.format, i64 0, i64 0",
                "  %written32 = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %data, i64 64, ptr %format, double %value)",
                "  %ignored = call ptr @uselocale(ptr %previous)",
                "  call void @freelocale(ptr %locale)",
                "  %written = sext i32 %written32 to i64",
                "  %result = call ptr @aether_string_from_utf8(ptr %data, i64 %written)",
                "  ret ptr %result",
                "panic:",
                "  call void @aether_text_range_panic()",
                "  unreachable",
                "}",
            ]),
            '\n'.join([
                "define private ptr @aether_text_concat_fragments(ptr %list) {",
                "entry:",
                "  %length_field = getelementptr %AetherList, ptr %list, i32 0, i32 0",
                "  %count = load i64, ptr %length_field",
                "  %data_field = getelementptr %AetherList, ptr %list, i32 0, i32 2",
                "  %fragments = load ptr, ptr %data_field",
                "  br label %sum_loop",
                "sum_loop:",
                "  %sum_index = phi i64 [ 0, %entry ], [ %sum_next, %sum_fragment ]",
                "  %total = phi i64 [ 0, %entry ], [ %next_total, %sum_fragment ]",
                "  %sum_done = icmp eq i64 %sum_index, %count",
                "  br i1 %sum_done, label %sum_finish, label %sum_fragment",
                "sum_fragment:",
                "  %sum_slot = getelementptr ptr, ptr %fragments, i64 %sum_index",
                "  %sum_value = load ptr, ptr %sum_slot",
                "  call void @aether_string_validate(ptr %sum_value)",
                "  %fragment_length = call i64 @aether_string_byte_length(ptr %sum_value)",
                "  %sum_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %total, i64 %fragment_length)",
                "  %next_total = extractvalue { i64, i1 } %sum_pair, 0",
                "  %sum_overflow = extractvalue { i64, i1 } %sum_pair, 1",
                "  %sum_next = add i64 %sum_index, 1",
                "  br i1 %sum_overflow, label %panic, label %sum_loop",
                "sum_finish:",
                "  %empty = icmp eq i64 %total, 0",
                "  br i1 %empty, label %return_empty, label %allocate_size",
                "allocate_size:",
                "  %payload_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %total, i64 1)",
                "  %payload_size = extractvalue { i64, i1 } %payload_pair, 0",
                "  %payload_overflow = extractvalue { i64, i1 } %payload_pair, 1",
                "  %object_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %payload_size, i64 24)",
                "  %object_size = extractvalue { i64, i1 } %object_pair, 0",
                "  %object_overflow = extractvalue { i64, i1 } %object_pair, 1",
                "  %size_overflow = or i1 %payload_overflow, %object_overflow",
                "  br i1 %size_overflow, label %panic, label %allocate",
                "allocate:",
                "  %object = call noalias ptr @malloc(i64 %object_size)",
                "  %failed = icmp eq ptr %object, null",
                "  br i1 %failed, label %panic, label %initialize",
                "initialize:",
                "  store i64 %total, ptr %object",
                "  %count_ptr = getelementptr i8, ptr %object, i64 8",
                "  store i64 1, ptr %count_ptr",
                "  %flags_ptr = getelementptr i8, ptr %object, i64 16",
                "  store i32 2, ptr %flags_ptr",
                "  %reserved_ptr = getelementptr i8, ptr %object, i64 20",
                "  store i32 0, ptr %reserved_ptr",
                "  %destination = getelementptr i8, ptr %object, i64 24",
                "  br label %copy_loop",
                "copy_loop:",
                "  %copy_index = phi i64 [ 0, %initialize ], [ %copy_next, %copy_fragment ]",
                "  %offset = phi i64 [ 0, %initialize ], [ %next_offset, %copy_fragment ]",
                "  %copy_done = icmp eq i64 %copy_index, %count",
                "  br i1 %copy_done, label %finish, label %copy_fragment",
                "copy_fragment:",
                "  %copy_slot = getelementptr ptr, ptr %fragments, i64 %copy_index",
                "  %copy_value = load ptr, ptr %copy_slot",
                "  %copy_length = call i64 @aether_string_byte_length(ptr %copy_value)",
                "  %copy_data = call ptr @aether_string_data(ptr %copy_value)",
                "  %copy_destination = getelementptr i8, ptr %destination, i64 %offset",
                "  call void @llvm.memcpy.p0.p0.i64(ptr %copy_destination, ptr %copy_data, i64 %copy_length, i1 false)",
                "  %next_offset = add i64 %offset, %copy_length",
                "  %copy_next = add i64 %copy_index, 1",
                "  br label %copy_loop",
                "finish:",
                "  %terminator = getelementptr i8, ptr %destination, i64 %total",
                "  store i8 0, ptr %terminator",
                "  ret ptr %object",
                "return_empty:",
                "  ret ptr @.aether.string.empty",
                "panic:",
                "  call void @aether_string_size_panic()",
                "  unreachable",
                "}",
            ]),
        ])

    @staticmethod
    def _parse_int() -> str:
        return "\n".join([
            "define private %struct.IntParseResult @aether_parse_int(ptr %value) {",
            "entry:",
            "  call void @aether_string_validate(ptr %value)",
            "  %length = call i64 @aether_string_byte_length(ptr %value)",
            "  %empty = icmp eq i64 %length, 0",
            "  br i1 %empty, label %return_empty, label %prepare",
            "prepare:",
            "  %data = call ptr @aether_string_data(ptr %value)",
            "  %first = load i8, ptr %data",
            "  %plus = icmp eq i8 %first, 43",
            "  %minus = icmp eq i8 %first, 45",
            "  %has_sign = or i1 %plus, %minus",
            "  %start = select i1 %has_sign, i64 1, i64 0",
            "  %only_sign = icmp eq i64 %start, %length",
            "  br i1 %only_sign, label %return_invalid, label %loop",
            "loop:",
            "  %index = phi i64 [ %start, %prepare ], [ %next_index, %accumulate ]",
            "  %magnitude = phi i64 [ 0, %prepare ], [ %next_magnitude, %accumulate ]",
            "  %overflowed = phi i1 [ false, %prepare ], [ %next_overflowed, %accumulate ]",
            "  %done = icmp eq i64 %index, %length",
            "  br i1 %done, label %finish, label %digit",
            "digit:",
            "  %byte_ptr = getelementptr i8, ptr %data, i64 %index",
            "  %byte = load i8, ptr %byte_ptr",
            "  %at_least_zero = icmp uge i8 %byte, 48",
            "  %at_most_nine = icmp ule i8 %byte, 57",
            "  %is_digit = and i1 %at_least_zero, %at_most_nine",
            "  br i1 %is_digit, label %range, label %return_invalid",
            "range:",
            "  %digit8 = sub i8 %byte, 48",
            "  %digit64 = zext i8 %digit8 to i64",
            "  %limit = select i1 %minus, i64 2147483648, i64 2147483647",
            "  %remaining = sub i64 %limit, %digit64",
            "  %maximum_before = udiv i64 %remaining, 10",
            "  %overflow = icmp ugt i64 %magnitude, %maximum_before",
            "  br label %accumulate",
            "accumulate:",
            "  %scaled = mul i64 %magnitude, 10",
            "  %candidate_magnitude = add i64 %scaled, %digit64",
            "  %next_overflowed = or i1 %overflowed, %overflow",
            "  %next_magnitude = select i1 %next_overflowed, i64 %magnitude, i64 %candidate_magnitude",
            "  %next_index = add i64 %index, 1",
            "  br label %loop",
            "finish:",
            "  br i1 %overflowed, label %return_range, label %success",
            "success:",
            "  %negative_value = sub i64 0, %magnitude",
            "  %signed_value = select i1 %minus, i64 %negative_value, i64 %magnitude",
            "  %result_value = trunc i64 %signed_value to i32",
            "  %success_value = insertvalue %struct.IntParseResult undef, i32 %result_value, 0",
            "  %success_result = insertvalue %struct.IntParseResult %success_value, i32 0, 1",
            "  ret %struct.IntParseResult %success_result",
            "return_empty:",
            "  %empty_value = insertvalue %struct.IntParseResult undef, i32 0, 0",
            "  %empty_result = insertvalue %struct.IntParseResult %empty_value, i32 1, 1",
            "  ret %struct.IntParseResult %empty_result",
            "return_invalid:",
            "  %invalid_value = insertvalue %struct.IntParseResult undef, i32 0, 0",
            "  %invalid_result = insertvalue %struct.IntParseResult %invalid_value, i32 2, 1",
            "  ret %struct.IntParseResult %invalid_result",
            "return_range:",
            "  %range_value = insertvalue %struct.IntParseResult undef, i32 0, 0",
            "  %range_result = insertvalue %struct.IntParseResult %range_value, i32 3, 1",
            "  ret %struct.IntParseResult %range_result",
            "}",
        ])

    @staticmethod
    def _parse_double() -> str:
        return "\n".join([
            "define private %struct.DoubleParseResult @aether_parse_double(ptr %value) {",
            "entry:",
            "  call void @aether_string_validate(ptr %value)",
            "  %length = call i64 @aether_string_byte_length(ptr %value)",
            "  %empty = icmp eq i64 %length, 0",
            "  br i1 %empty, label %return_empty, label %prepare",
            "prepare:",
            "  %data = call ptr @aether_string_data(ptr %value)",
            "  %first = load i8, ptr %data",
            "  %plus = icmp eq i8 %first, 43",
            "  %minus = icmp eq i8 %first, 45",
            "  %has_sign = or i1 %plus, %minus",
            "  %start = select i1 %has_sign, i64 1, i64 0",
            "  %only_sign = icmp eq i64 %start, %length",
            "  br i1 %only_sign, label %return_invalid, label %loop",
            "loop:",
            "  %index = phi i64 [ %start, %prepare ], [ %next_index, %advance ]",
            "  %state = phi i32 [ 0, %prepare ], [ %next_state, %advance ]",
            "  %seen_digit = phi i1 [ false, %prepare ], [ %next_seen_digit, %advance ]",
            "  %seen_dot = phi i1 [ false, %prepare ], [ %next_seen_dot, %advance ]",
            "  %done = icmp eq i64 %index, %length",
            "  br i1 %done, label %finish_grammar, label %classify",
            "classify:",
            "  %byte_ptr = getelementptr i8, ptr %data, i64 %index",
            "  %byte = load i8, ptr %byte_ptr",
            "  %ge_zero = icmp uge i8 %byte, 48",
            "  %le_nine = icmp ule i8 %byte, 57",
            "  %digit = and i1 %ge_zero, %le_nine",
            "  %dot = icmp eq i8 %byte, 46",
            "  %lower_e = icmp eq i8 %byte, 101",
            "  %upper_e = icmp eq i8 %byte, 69",
            "  %is_e = or i1 %lower_e, %upper_e",
            "  %exp_plus = icmp eq i8 %byte, 43",
            "  %exp_minus = icmp eq i8 %byte, 45",
            "  %exp_sign = or i1 %exp_plus, %exp_minus",
            "  %mantissa = icmp eq i32 %state, 0",
            "  %exp_start = icmp eq i32 %state, 1",
            "  br i1 %mantissa, label %mantissa_char, label %exponent_char",
            "mantissa_char:",
            "  br i1 %digit, label %mantissa_digit, label %mantissa_other",
            "mantissa_digit:",
            "  br label %advance",
            "mantissa_other:",
            "  %new_dot = and i1 %dot, %seen_dot",
            "  br i1 %dot, label %dot_check, label %exponent_marker_check",
            "dot_check:",
            "  br i1 %new_dot, label %return_invalid, label %advance",
            "exponent_marker_check:",
            "  %valid_e = and i1 %is_e, %seen_digit",
            "  br i1 %valid_e, label %advance, label %return_invalid",
            "exponent_char:",
            "  br i1 %digit, label %advance, label %exponent_non_digit",
            "exponent_non_digit:",
            "  %allowed_sign = and i1 %exp_start, %exp_sign",
            "  br i1 %allowed_sign, label %advance, label %return_invalid",
            "advance:",
            "  %is_e_here = or i1 %lower_e, %upper_e",
            "  %to_exp_start = and i1 %mantissa, %is_e_here",
            "  %to_exp_after_sign = and i1 %exp_start, %exp_sign",
            "  %in_exp = xor i1 %mantissa, true",
            "  %exp_digit = and i1 %in_exp, %digit",
            "  %state_after_e = select i1 %to_exp_start, i32 1, i32 %state",
            "  %state_after_sign = select i1 %to_exp_after_sign, i32 2, i32 %state_after_e",
            "  %next_state = select i1 %exp_digit, i32 3, i32 %state_after_sign",
            "  %mantissa_digit_seen = and i1 %mantissa, %digit",
            "  %next_seen_digit = or i1 %seen_digit, %mantissa_digit_seen",
            "  %dot_here = and i1 %mantissa, %dot",
            "  %next_seen_dot = or i1 %seen_dot, %dot_here",
            "  %next_index = add i64 %index, 1",
            "  br label %loop",
            "finish_grammar:",
            "  %no_exponent = icmp eq i32 %state, 0",
            "  %complete_exponent = icmp eq i32 %state, 3",
            "  %complete = or i1 %no_exponent, %complete_exponent",
            "  %grammar_ok = and i1 %seen_digit, %complete",
            "  br i1 %grammar_ok, label %convert, label %return_invalid",
            "convert:",
            "  %locale_name = getelementptr [2 x i8], ptr @.aether.locale.c, i64 0, i64 0",
            "  %locale = call ptr @newlocale(i32 2, ptr %locale_name, ptr null)",
            "  %locale_failed = icmp eq ptr %locale, null",
            "  br i1 %locale_failed, label %locale_panic, label %convert_number",
            "locale_panic:",
            "  call void @aether_string_locale_panic()",
            "  unreachable",
            "convert_number:",
            "  %parsed = call double @strtod_l(ptr %data, ptr null, ptr %locale)",
            "  call void @freelocale(ptr %locale)",
            "  %positive_inf = fcmp oeq double %parsed, 0x7FF0000000000000",
            "  %negative_inf = fcmp oeq double %parsed, 0xFFF0000000000000",
            "  %overflow = or i1 %positive_inf, %negative_inf",
            "  br i1 %overflow, label %return_range, label %success",
            "success:",
            "  %success_value = insertvalue %struct.DoubleParseResult undef, double %parsed, 0",
            "  %success_result = insertvalue %struct.DoubleParseResult %success_value, i32 0, 1",
            "  ret %struct.DoubleParseResult %success_result",
            "return_empty:",
            "  %empty_value = insertvalue %struct.DoubleParseResult undef, double 0.0, 0",
            "  %empty_result = insertvalue %struct.DoubleParseResult %empty_value, i32 1, 1",
            "  ret %struct.DoubleParseResult %empty_result",
            "return_invalid:",
            "  %invalid_value = insertvalue %struct.DoubleParseResult undef, double 0.0, 0",
            "  %invalid_result = insertvalue %struct.DoubleParseResult %invalid_value, i32 2, 1",
            "  ret %struct.DoubleParseResult %invalid_result",
            "return_range:",
            "  %range_value = insertvalue %struct.DoubleParseResult undef, double 0.0, 0",
            "  %range_result = insertvalue %struct.DoubleParseResult %range_value, i32 3, 1",
            "  ret %struct.DoubleParseResult %range_result",
            "}",
        ])

    @staticmethod
    def _panic_data() -> str:
        messages = (
            ("descriptor", "Aether panic: invalid string descriptor"),
            ("rc_overflow", "Aether panic: string reference count overflow"),
            ("rc_underflow", "Aether panic: string reference count underflow"),
            ("utf8", "Aether panic: invalid UTF-8 string data"),
            ("size", "Aether panic: string allocation size overflow"),
            ("length", "Aether panic: string byte length does not fit in int"),
            ("locale", "Aether panic: cannot create C numeric locale"),
            ("oom", "Aether panic: string allocation failed"),
        )
        chunks: list[str] = []
        for key, message in messages:
            size = len(message.encode("utf-8")) + 1
            chunks.append(
                f'@.aether.string.{key} = private unnamed_addr constant [{size} x i8] c"{message}\\00"'
            )
            chunks.append("\n".join([
                f"define private void @aether_string_{key}_panic() noreturn {{",
                "entry:",
                f"  %message = getelementptr [{size} x i8], ptr @.aether.string.{key}, i64 0, i64 0",
                "  call i32 @puts(ptr %message)",
                "  call void @exit(i32 1)",
                "  unreachable",
                "}",
            ]))
        return "\n\n".join(chunks)

    @staticmethod
    def _validate_descriptor() -> str:
        return "\n".join([
            "define private void @aether_string_validate(ptr %value) {",
            "entry:",
            "  %null = icmp eq ptr %value, null",
            "  br i1 %null, label %panic, label %header",
            "header:",
            "  %flags_ptr = getelementptr i8, ptr %value, i64 16",
            "  %flags = load i32, ptr %flags_ptr",
            "  %reserved_ptr = getelementptr i8, ptr %value, i64 20",
            "  %reserved = load i32, ptr %reserved_ptr",
            "  %unknown = and i32 %flags, -4",
            "  %known = icmp eq i32 %unknown, 0",
            "  %valid_mask = and i32 %flags, 2",
            "  %utf8 = icmp ne i32 %valid_mask, 0",
            "  %reserved_zero = icmp eq i32 %reserved, 0",
            "  %flags_ok = and i1 %known, %utf8",
            "  %ok = and i1 %flags_ok, %reserved_zero",
            "  br i1 %ok, label %done, label %panic",
            "panic:",
            "  call void @aether_string_descriptor_panic()",
            "  unreachable",
            "done:",
            "  ret void",
            "}",
        ])

    @staticmethod
    def _accessors() -> str:
        return "\n\n".join([
            "\n".join([
                "define private ptr @aether_string_empty() {",
                "entry:",
                "  ret ptr @.aether.string.empty",
                "}",
            ]),
            "\n".join([
                "define private i64 @aether_string_byte_length(ptr %value) {",
                "entry:",
                "  call void @aether_string_validate(ptr %value)",
                "  %length = load i64, ptr %value",
                "  %negative = icmp slt i64 %length, 0",
                "  br i1 %negative, label %panic, label %done",
                "panic:",
                "  call void @aether_string_descriptor_panic()",
                "  unreachable",
                "done:",
                "  ret i64 %length",
                "}",
            ]),
            "\n".join([
                "define private i32 @aether_string_byte_length_to_int(i64 %length) {",
                "entry:",
                "  %negative = icmp slt i64 %length, 0",
                "  %too_large = icmp sgt i64 %length, 2147483647",
                "  %invalid = or i1 %negative, %too_large",
                "  br i1 %invalid, label %panic, label %convert",
                "panic:",
                "  call void @aether_string_length_panic()",
                "  unreachable",
                "convert:",
                "  %result = trunc i64 %length to i32",
                "  ret i32 %result",
                "}",
            ]),
            "\n".join([
                "define private ptr @aether_string_data(ptr %value) {",
                "entry:",
                "  call void @aether_string_validate(ptr %value)",
                "  %data = getelementptr i8, ptr %value, i64 24",
                "  ret ptr %data",
                "}",
            ]),
        ])

    @staticmethod
    def _retain() -> str:
        return "\n".join([
            "define private void @aether_string_retain(ptr %value) {",
            "entry:",
            "  call void @aether_string_validate(ptr %value)",
            "  %flags_ptr = getelementptr i8, ptr %value, i64 16",
            "  %flags = load i32, ptr %flags_ptr",
            "  %immortal_mask = and i32 %flags, 1",
            "  %immortal = icmp ne i32 %immortal_mask, 0",
            "  br i1 %immortal, label %done, label %owned",
            "owned:",
            "  %count_ptr = getelementptr i8, ptr %value, i64 8",
            "  %count = load i64, ptr %count_ptr",
            "  %overflow = icmp eq i64 %count, 9223372036854775807",
            "  %invalid = icmp sle i64 %count, 0",
            "  %bad = or i1 %overflow, %invalid",
            "  br i1 %bad, label %panic, label %increment",
            "panic:",
            "  call void @aether_string_rc_overflow_panic()",
            "  unreachable",
            "increment:",
            "  %next = add i64 %count, 1",
            "  store i64 %next, ptr %count_ptr",
            "  br label %done",
            "done:",
            "  ret void",
            "}",
        ])

    @staticmethod
    def _release() -> str:
        return "\n".join([
            "define private void @aether_string_release(ptr %value) {",
            "entry:",
            "  call void @aether_string_validate(ptr %value)",
            "  %flags_ptr = getelementptr i8, ptr %value, i64 16",
            "  %flags = load i32, ptr %flags_ptr",
            "  %immortal_mask = and i32 %flags, 1",
            "  %immortal = icmp ne i32 %immortal_mask, 0",
            "  br i1 %immortal, label %done, label %owned",
            "owned:",
            "  %count_ptr = getelementptr i8, ptr %value, i64 8",
            "  %count = load i64, ptr %count_ptr",
            "  %invalid = icmp sle i64 %count, 0",
            "  br i1 %invalid, label %panic, label %decrement",
            "panic:",
            "  call void @aether_string_rc_underflow_panic()",
            "  unreachable",
            "decrement:",
            "  %last = icmp eq i64 %count, 1",
            "  br i1 %last, label %free, label %store",
            "store:",
            "  %next = sub i64 %count, 1",
            "  store i64 %next, ptr %count_ptr",
            "  br label %done",
            "free:",
            "  store i64 0, ptr %count_ptr",
            "  call void @free(ptr %value)",
            "  br label %done",
            "done:",
            "  ret void",
            "}",
        ])

    @staticmethod
    def _equal() -> str:
        return "\n".join([
            "define private i1 @aether_string_equal(ptr %left, ptr %right) {",
            "entry:",
            "  call void @aether_string_validate(ptr %left)",
            "  call void @aether_string_validate(ptr %right)",
            "  %same_handle = icmp eq ptr %left, %right",
            "  br i1 %same_handle, label %equal, label %lengths",
            "lengths:",
            "  %left_length = call i64 @aether_string_byte_length(ptr %left)",
            "  %right_length = call i64 @aether_string_byte_length(ptr %right)",
            "  %same_length = icmp eq i64 %left_length, %right_length",
            "  br i1 %same_length, label %empty_check, label %different",
            "empty_check:",
            "  %empty = icmp eq i64 %left_length, 0",
            "  br i1 %empty, label %equal, label %bytes",
            "bytes:",
            "  %left_data = getelementptr i8, ptr %left, i64 24",
            "  %right_data = getelementptr i8, ptr %right, i64 24",
            "  %comparison = call i32 @memcmp(ptr %left_data, ptr %right_data, i64 %left_length)",
            "  %same_bytes = icmp eq i32 %comparison, 0",
            "  ret i1 %same_bytes",
            "equal:",
            "  ret i1 true",
            "different:",
            "  ret i1 false",
            "}",
        ])

    @staticmethod
    def _concat() -> str:
        return "\n".join([
            "define private ptr @aether_string_concat(ptr %left, ptr %right) {",
            "entry:",
            "  call void @aether_string_validate(ptr %left)",
            "  call void @aether_string_validate(ptr %right)",
            "  %left_length = call i64 @aether_string_byte_length(ptr %left)",
            "  %right_length = call i64 @aether_string_byte_length(ptr %right)",
            "  %left_empty = icmp eq i64 %left_length, 0",
            "  %right_empty = icmp eq i64 %right_length, 0",
            "  %both_empty = and i1 %left_empty, %right_empty",
            "  br i1 %both_empty, label %return_empty, label %left_check",
            "return_empty:",
            "  ret ptr @.aether.string.empty",
            "left_check:",
            "  br i1 %left_empty, label %return_right, label %right_check",
            "return_right:",
            "  call void @aether_string_retain(ptr %right)",
            "  ret ptr %right",
            "right_check:",
            "  br i1 %right_empty, label %return_left, label %sum",
            "return_left:",
            "  call void @aether_string_retain(ptr %left)",
            "  ret ptr %left",
            "sum:",
            "  %length_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %left_length, i64 %right_length)",
            "  %length = extractvalue { i64, i1 } %length_pair, 0",
            "  %length_overflow = extractvalue { i64, i1 } %length_pair, 1",
            "  %length_too_large = icmp ugt i64 %length, 9223372036854775807",
            "  %bad_length = or i1 %length_overflow, %length_too_large",
            "  br i1 %bad_length, label %size_panic, label %payload_size",
            "payload_size:",
            "  %payload_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %length, i64 1)",
            "  %payload = extractvalue { i64, i1 } %payload_pair, 0",
            "  %payload_overflow = extractvalue { i64, i1 } %payload_pair, 1",
            "  br i1 %payload_overflow, label %size_panic, label %total_size",
            "total_size:",
            "  %total_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %payload, i64 24)",
            "  %total = extractvalue { i64, i1 } %total_pair, 0",
            "  %total_overflow = extractvalue { i64, i1 } %total_pair, 1",
            "  %total_too_large = icmp ugt i64 %total, 9223372036854775807",
            "  %bad_total = or i1 %total_overflow, %total_too_large",
            "  br i1 %bad_total, label %size_panic, label %allocate",
            "size_panic:",
            "  call void @aether_string_size_panic()",
            "  unreachable",
            "allocate:",
            "  %object = call noalias ptr @malloc(i64 %total)",
            "  %failed = icmp eq ptr %object, null",
            "  br i1 %failed, label %oom, label %initialize",
            "oom:",
            "  call void @aether_string_oom_panic()",
            "  unreachable",
            "initialize:",
            "  store i64 %length, ptr %object",
            "  %count_ptr = getelementptr i8, ptr %object, i64 8",
            "  store i64 1, ptr %count_ptr",
            "  %flags_ptr = getelementptr i8, ptr %object, i64 16",
            "  store i32 2, ptr %flags_ptr",
            "  %reserved_ptr = getelementptr i8, ptr %object, i64 20",
            "  store i32 0, ptr %reserved_ptr",
            "  %data = getelementptr i8, ptr %object, i64 24",
            "  %left_data = getelementptr i8, ptr %left, i64 24",
            "  call void @llvm.memcpy.p0.p0.i64(ptr %data, ptr %left_data, i64 %left_length, i1 false)",
            "  %right_destination = getelementptr i8, ptr %data, i64 %left_length",
            "  %right_data = getelementptr i8, ptr %right, i64 24",
            "  call void @llvm.memcpy.p0.p0.i64(ptr %right_destination, ptr %right_data, i64 %right_length, i1 false)",
            "  %terminator = getelementptr i8, ptr %data, i64 %length",
            "  store i8 0, ptr %terminator",
            "  ret ptr %object",
            "}",
        ])

    @staticmethod
    def _trim() -> str:
        # Aether v1 trims exactly six ASCII whitespace bytes.  Each is a
        # single-byte UTF-8 code unit and cannot occur inside a multibyte UTF-8
        # sequence, so scanning the two byte boundaries preserves valid UTF-8.
        return "\n\n".join([
            "\n".join([
                "define private i1 @aether_string_is_ascii_whitespace(i8 %byte) {",
                "entry:",
                "  switch i8 %byte, label %not_whitespace [",
                "    i8 32, label %whitespace",
                "    i8 9, label %whitespace",
                "    i8 10, label %whitespace",
                "    i8 13, label %whitespace",
                "    i8 12, label %whitespace",
                "    i8 11, label %whitespace",
                "  ]",
                "whitespace:",
                "  ret i1 true",
                "not_whitespace:",
                "  ret i1 false",
                "}",
            ]),
            "\n".join([
                "define private ptr @aether_string_trim(ptr %value) {",
                "entry:",
                "  call void @aether_string_validate(ptr %value)",
                "  %length = call i64 @aether_string_byte_length(ptr %value)",
                "  %empty = icmp eq i64 %length, 0",
                "  br i1 %empty, label %return_empty, label %prepare",
                "prepare:",
                "  %data = call ptr @aether_string_data(ptr %value)",
                "  br label %start_loop",
                "start_loop:",
                "  %start = phi i64 [ 0, %prepare ], [ %next_start, %start_whitespace ]",
                "  %start_at_end = icmp eq i64 %start, %length",
                "  br i1 %start_at_end, label %return_empty, label %inspect_start",
                "inspect_start:",
                "  %start_ptr = getelementptr i8, ptr %data, i64 %start",
                "  %start_byte = load i8, ptr %start_ptr",
                "  %leading_whitespace = call i1 @aether_string_is_ascii_whitespace(i8 %start_byte)",
                "  br i1 %leading_whitespace, label %start_whitespace, label %end_loop",
                "start_whitespace:",
                "  %next_start = add i64 %start, 1",
                "  br label %start_loop",
                "end_loop:",
                "  %end = phi i64 [ %length, %inspect_start ], [ %candidate, %end_whitespace ]",
                "  %candidate = sub i64 %end, 1",
                "  %end_ptr = getelementptr i8, ptr %data, i64 %candidate",
                "  %end_byte = load i8, ptr %end_ptr",
                "  %trailing_whitespace = call i1 @aether_string_is_ascii_whitespace(i8 %end_byte)",
                "  br i1 %trailing_whitespace, label %end_whitespace, label %finish",
                "end_whitespace:",
                "  br label %end_loop",
                "finish:",
                "  %unchanged_start = icmp eq i64 %start, 0",
                "  %unchanged_end = icmp eq i64 %end, %length",
                "  %unchanged = and i1 %unchanged_start, %unchanged_end",
                "  br i1 %unchanged, label %return_original, label %copy_range",
                "return_original:",
                "  call void @aether_string_retain(ptr %value)",
                "  ret ptr %value",
                "copy_range:",
                "  %trimmed_length = sub i64 %end, %start",
                "  %trimmed_data = getelementptr i8, ptr %data, i64 %start",
                "  %result = call ptr @aether_string_from_utf8(ptr %trimmed_data, i64 %trimmed_length)",
                "  ret ptr %result",
                "return_empty:",
                "  ret ptr @.aether.string.empty",
                "}",
            ]),
        ])

    @staticmethod
    def _split() -> str:
        # Left-to-right exact byte matching.  Advancing by separator length
        # after a match makes candidates non-overlapping.  The first pass
        # obtains an exact Array length; the second creates owned fragments.
        return "\n".join([
            '@.aether.string.split.empty = private unnamed_addr constant [53 x i8] c"Aether panic: string split separator cannot be empty\\00"',
            "define private void @aether_string_split_empty_panic() noreturn {",
            "entry:",
            "  %message = getelementptr [53 x i8], ptr @.aether.string.split.empty, i64 0, i64 0",
            "  call i32 @puts(ptr %message)",
            "  call void @exit(i32 1)",
            "  unreachable",
            "}",
            "define private ptr @aether_string_split(ptr %text, ptr %separator) {",
            "entry:",
            "  call void @aether_string_validate(ptr %text)",
            "  call void @aether_string_validate(ptr %separator)",
            "  %text_length = call i64 @aether_string_byte_length(ptr %text)",
            "  %separator_length = call i64 @aether_string_byte_length(ptr %separator)",
            "  %separator_empty = icmp eq i64 %separator_length, 0",
            "  br i1 %separator_empty, label %empty_separator, label %prepare",
            "empty_separator:",
            "  call void @aether_string_split_empty_panic()",
            "  unreachable",
            "prepare:",
            "  %text_data = call ptr @aether_string_data(ptr %text)",
            "  %separator_data = call ptr @aether_string_data(ptr %separator)",
            "  br label %count_loop",
            "count_loop:",
            "  %count_index = phi i64 [ 0, %prepare ], [ %count_next_index, %count_advance ]",
            "  %matches = phi i64 [ 0, %prepare ], [ %count_next_matches, %count_advance ]",
            "  %count_remaining = sub i64 %text_length, %count_index",
            "  %count_can_match = icmp uge i64 %count_remaining, %separator_length",
            "  br i1 %count_can_match, label %count_compare, label %count_done",
            "count_compare:",
            "  %count_candidate = getelementptr i8, ptr %text_data, i64 %count_index",
            "  %count_comparison = call i32 @memcmp(ptr %count_candidate, ptr %separator_data, i64 %separator_length)",
            "  %count_matched = icmp eq i32 %count_comparison, 0",
            "  br i1 %count_matched, label %count_match, label %count_miss",
            "count_match:",
            "  %match_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %matches, i64 1)",
            "  %matched_count = extractvalue { i64, i1 } %match_pair, 0",
            "  %match_overflow = extractvalue { i64, i1 } %match_pair, 1",
            "  br i1 %match_overflow, label %size_panic, label %count_match_advance",
            "count_match_advance:",
            "  %index_after_match = add i64 %count_index, %separator_length",
            "  br label %count_advance",
            "count_miss:",
            "  %index_after_miss = add i64 %count_index, 1",
            "  br label %count_advance",
            "count_advance:",
            "  %count_next_index = phi i64 [ %index_after_match, %count_match_advance ], [ %index_after_miss, %count_miss ]",
            "  %count_next_matches = phi i64 [ %matched_count, %count_match_advance ], [ %matches, %count_miss ]",
            "  br label %count_loop",
            "count_done:",
            "  %part_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %matches, i64 1)",
            "  %part_count = extractvalue { i64, i1 } %part_pair, 0",
            "  %part_overflow = extractvalue { i64, i1 } %part_pair, 1",
            "  br i1 %part_overflow, label %size_panic, label %allocate",
            "size_panic:",
            "  call void @aether_string_size_panic()",
            "  unreachable",
            "allocate:",
            "  %result = call ptr @aether_array_new(i64 ptrtoint (ptr getelementptr (ptr, ptr null, i64 1) to i64), i64 %part_count)",
            "  %data_field = getelementptr %AetherArray, ptr %result, i32 0, i32 1",
            "  %result_data = load ptr, ptr %data_field",
            "  %no_matches = icmp eq i64 %matches, 0",
            "  br i1 %no_matches, label %return_original, label %split_loop",
            "return_original:",
            "  call void @aether_string_retain(ptr %text)",
            "  store ptr %text, ptr %result_data",
            "  ret ptr %result",
            "split_loop:",
            "  %split_index = phi i64 [ 0, %allocate ], [ %split_next_index, %split_advance ]",
            "  %fragment_start = phi i64 [ 0, %allocate ], [ %split_next_start, %split_advance ]",
            "  %part_index = phi i64 [ 0, %allocate ], [ %split_next_part, %split_advance ]",
            "  %split_remaining = sub i64 %text_length, %split_index",
            "  %split_can_match = icmp uge i64 %split_remaining, %separator_length",
            "  br i1 %split_can_match, label %split_compare, label %store_final",
            "split_compare:",
            "  %split_candidate = getelementptr i8, ptr %text_data, i64 %split_index",
            "  %split_comparison = call i32 @memcmp(ptr %split_candidate, ptr %separator_data, i64 %separator_length)",
            "  %split_matched = icmp eq i32 %split_comparison, 0",
            "  br i1 %split_matched, label %store_fragment, label %split_miss",
            "store_fragment:",
            "  %fragment_length = sub i64 %split_index, %fragment_start",
            "  %fragment_data = getelementptr i8, ptr %text_data, i64 %fragment_start",
            "  %fragment = call ptr @aether_string_from_utf8(ptr %fragment_data, i64 %fragment_length)",
            "  %fragment_slot = getelementptr ptr, ptr %result_data, i64 %part_index",
            "  store ptr %fragment, ptr %fragment_slot",
            "  %index_after_fragment = add i64 %split_index, %separator_length",
            "  %part_after_fragment = add i64 %part_index, 1",
            "  br label %split_advance",
            "split_miss:",
            "  %index_after_split_miss = add i64 %split_index, 1",
            "  br label %split_advance",
            "split_advance:",
            "  %split_next_index = phi i64 [ %index_after_fragment, %store_fragment ], [ %index_after_split_miss, %split_miss ]",
            "  %split_next_start = phi i64 [ %index_after_fragment, %store_fragment ], [ %fragment_start, %split_miss ]",
            "  %split_next_part = phi i64 [ %part_after_fragment, %store_fragment ], [ %part_index, %split_miss ]",
            "  br label %split_loop",
            "store_final:",
            "  %final_length = sub i64 %text_length, %fragment_start",
            "  %final_data = getelementptr i8, ptr %text_data, i64 %fragment_start",
            "  %final_fragment = call ptr @aether_string_from_utf8(ptr %final_data, i64 %final_length)",
            "  %final_slot = getelementptr ptr, ptr %result_data, i64 %part_index",
            "  store ptr %final_fragment, ptr %final_slot",
            "  ret ptr %result",
            "}",
        ])

    @staticmethod
    def _compare() -> str:
        return "\n".join([
            "define private i32 @aether_string_compare_bytes(ptr %left, ptr %right) {",
            "entry:",
            "  call void @aether_string_validate(ptr %left)",
            "  call void @aether_string_validate(ptr %right)",
            "  %same = icmp eq ptr %left, %right",
            "  br i1 %same, label %equal, label %lengths",
            "lengths:",
            "  %left_length = load i64, ptr %left",
            "  %right_length = load i64, ptr %right",
            "  %left_shorter = icmp ult i64 %left_length, %right_length",
            "  %minimum = select i1 %left_shorter, i64 %left_length, i64 %right_length",
            "  %empty = icmp eq i64 %minimum, 0",
            "  br i1 %empty, label %prefix, label %bytes",
            "bytes:",
            "  %left_data = getelementptr i8, ptr %left, i64 24",
            "  %right_data = getelementptr i8, ptr %right, i64 24",
            "  %comparison = call i32 @memcmp(ptr %left_data, ptr %right_data, i64 %minimum)",
            "  %bytes_equal = icmp eq i32 %comparison, 0",
            "  br i1 %bytes_equal, label %prefix, label %byte_result",
            "byte_result:",
            "  ret i32 %comparison",
            "prefix:",
            "  %same_length = icmp eq i64 %left_length, %right_length",
            "  br i1 %same_length, label %equal, label %ordered",
            "ordered:",
            "  %order = select i1 %left_shorter, i32 -1, i32 1",
            "  ret i32 %order",
            "equal:",
            "  ret i32 0",
            "}",
        ])

    @staticmethod
    def _print() -> str:
        return "\n".join([
            "define private void @aether_string_print(ptr %value) {",
            "entry:",
            "  %length = call i64 @aether_string_byte_length(ptr %value)",
            "  %empty = icmp eq i64 %length, 0",
            "  br i1 %empty, label %done, label %write",
            "write:",
            "  %data = call ptr @aether_string_data(ptr %value)",
            "  %stream = load ptr, ptr @stdout",
            "  %written = call i64 @fwrite(ptr %data, i64 1, i64 %length, ptr %stream)",
            "  br label %done",
            "done:",
            "  ret void",
            "}",
        ])

    @staticmethod
    def _print_escaped() -> str:
        return "\n".join([
            "define private void @aether_string_print_escaped(ptr %value) {",
            "entry:",
            "  %length = call i64 @aether_string_byte_length(ptr %value)",
            "  %data = call ptr @aether_string_data(ptr %value)",
            "  %stream = load ptr, ptr @stdout",
            "  br label %loop",
            "loop:",
            "  %index = phi i64 [ 0, %entry ], [ %next, %advance ]",
            "  %done = icmp eq i64 %index, %length",
            "  br i1 %done, label %finish, label %inspect",
            "inspect:",
            "  %byte_ptr = getelementptr i8, ptr %data, i64 %index",
            "  %byte = load i8, ptr %byte_ptr",
            "  %is_slash = icmp eq i8 %byte, 92",
            "  %is_quote = icmp eq i8 %byte, 34",
            "  %is_newline = icmp eq i8 %byte, 10",
            "  %is_tab = icmp eq i8 %byte, 9",
            "  %quote_or_slash = or i1 %is_slash, %is_quote",
            "  %newline_or_tab = or i1 %is_newline, %is_tab",
            "  %escaped = or i1 %quote_or_slash, %newline_or_tab",
            "  br i1 %escaped, label %escape, label %raw",
            "escape:",
            "  %slash_result = call i32 @putchar(i32 92)",
            "  %escaped_byte = select i1 %is_newline, i32 110, i32 116",
            "  %literal_byte = zext i8 %byte to i32",
            "  %rendered_byte = select i1 %newline_or_tab, i32 %escaped_byte, i32 %literal_byte",
            "  %escape_result = call i32 @putchar(i32 %rendered_byte)",
            "  br label %advance",
            "raw:",
            "  %raw_result = call i64 @fwrite(ptr %byte_ptr, i64 1, i64 1, ptr %stream)",
            "  br label %advance",
            "advance:",
            "  %next = add i64 %index, 1",
            "  br label %loop",
            "finish:",
            "  ret void",
            "}",
        ])

    @staticmethod
    def _utf8_validator() -> str:
        # Strict RFC 3629 ranges: rejects overlong forms, surrogates and values
        # above U+10FFFF while accepting embedded U+0000.
        return "\n".join([
            "define private i1 @aether_string_is_valid_utf8(ptr %data, i64 %length) {",
            "entry:",
            "  %negative = icmp slt i64 %length, 0",
            "  br i1 %negative, label %invalid, label %loop",
            "loop:",
            "  %index = phi i64 [ 0, %entry ], [ %next, %advance ]",
            "  %done = icmp eq i64 %index, %length",
            "  br i1 %done, label %valid, label %lead",
            "lead:",
            "  %p0 = getelementptr i8, ptr %data, i64 %index",
            "  %b0 = load i8, ptr %p0",
            "  %ascii = icmp ult i8 %b0, -128",
            "  br i1 %ascii, label %one, label %class2",
            "class2:",
            "  %two_low = icmp uge i8 %b0, -62",
            "  %two_high = icmp ule i8 %b0, -33",
            "  %two = and i1 %two_low, %two_high",
            "  br i1 %two, label %need2, label %class3",
            "class3:",
            "  %three_low = icmp uge i8 %b0, -32",
            "  %three_high = icmp ule i8 %b0, -17",
            "  %three = and i1 %three_low, %three_high",
            "  br i1 %three, label %need3, label %class4",
            "class4:",
            "  %four_low = icmp uge i8 %b0, -16",
            "  %four_high = icmp ule i8 %b0, -12",
            "  %four = and i1 %four_low, %four_high",
            "  br i1 %four, label %need4, label %invalid",
            "need2:",
            "  %remaining2 = sub i64 %length, %index",
            "  %enough2 = icmp uge i64 %remaining2, 2",
            "  br i1 %enough2, label %check2, label %invalid",
            "check2:",
            "  %i1_2 = add i64 %index, 1",
            "  %p1_2 = getelementptr i8, ptr %data, i64 %i1_2",
            "  %b1_2 = load i8, ptr %p1_2",
            "  %c1_2 = and i8 %b1_2, -64",
            "  %ok2 = icmp eq i8 %c1_2, -128",
            "  br i1 %ok2, label %two_advance, label %invalid",
            "need3:",
            "  %remaining3 = sub i64 %length, %index",
            "  %enough3 = icmp uge i64 %remaining3, 3",
            "  br i1 %enough3, label %check3, label %invalid",
            "check3:",
            "  %i1_3 = add i64 %index, 1",
            "  %i2_3 = add i64 %index, 2",
            "  %p1_3 = getelementptr i8, ptr %data, i64 %i1_3",
            "  %p2_3 = getelementptr i8, ptr %data, i64 %i2_3",
            "  %b1_3 = load i8, ptr %p1_3",
            "  %b2_3 = load i8, ptr %p2_3",
            "  %c2_3 = and i8 %b2_3, -64",
            "  %tail2_3 = icmp eq i8 %c2_3, -128",
            "  %is_e0 = icmp eq i8 %b0, -32",
            "  %is_ed = icmp eq i8 %b0, -19",
            "  %b1_normal_low = icmp uge i8 %b1_3, -128",
            "  %b1_normal_high = icmp ule i8 %b1_3, -65",
            "  %b1_normal = and i1 %b1_normal_low, %b1_normal_high",
            "  %b1_e0_low = icmp uge i8 %b1_3, -96",
            "  %b1_ed_high = icmp ule i8 %b1_3, -97",
            "  %not_e0 = xor i1 %is_e0, true",
            "  %not_ed = xor i1 %is_ed, true",
            "  %normal_lead = and i1 %not_e0, %not_ed",
            "  %normal_case = and i1 %normal_lead, %b1_normal",
            "  %e0_case = and i1 %is_e0, %b1_e0_low",
            "  %ed_case = and i1 %is_ed, %b1_ed_high",
            "  %special = or i1 %e0_case, %ed_case",
            "  %head_ok3 = or i1 %normal_case, %special",
            "  %ok3 = and i1 %head_ok3, %tail2_3",
            "  br i1 %ok3, label %three_advance, label %invalid",
            "need4:",
            "  %remaining4 = sub i64 %length, %index",
            "  %enough4 = icmp uge i64 %remaining4, 4",
            "  br i1 %enough4, label %check4, label %invalid",
            "check4:",
            "  %i1_4 = add i64 %index, 1",
            "  %i2_4 = add i64 %index, 2",
            "  %i3_4 = add i64 %index, 3",
            "  %p1_4 = getelementptr i8, ptr %data, i64 %i1_4",
            "  %p2_4 = getelementptr i8, ptr %data, i64 %i2_4",
            "  %p3_4 = getelementptr i8, ptr %data, i64 %i3_4",
            "  %b1_4 = load i8, ptr %p1_4",
            "  %b2_4 = load i8, ptr %p2_4",
            "  %b3_4 = load i8, ptr %p3_4",
            "  %c2_4 = and i8 %b2_4, -64",
            "  %c3_4 = and i8 %b3_4, -64",
            "  %tail2_4 = icmp eq i8 %c2_4, -128",
            "  %tail3_4 = icmp eq i8 %c3_4, -128",
            "  %tails4 = and i1 %tail2_4, %tail3_4",
            "  %is_f0 = icmp eq i8 %b0, -16",
            "  %is_f4 = icmp eq i8 %b0, -12",
            "  %b1_normal4_low = icmp uge i8 %b1_4, -128",
            "  %b1_normal4_high = icmp ule i8 %b1_4, -65",
            "  %b1_normal4 = and i1 %b1_normal4_low, %b1_normal4_high",
            "  %b1_f0_low = icmp uge i8 %b1_4, -112",
            "  %b1_f4_high = icmp ule i8 %b1_4, -113",
            "  %not_f0 = xor i1 %is_f0, true",
            "  %not_f4 = xor i1 %is_f4, true",
            "  %normal_lead4 = and i1 %not_f0, %not_f4",
            "  %normal_case4 = and i1 %normal_lead4, %b1_normal4",
            "  %f0_case = and i1 %is_f0, %b1_f0_low",
            "  %f4_case = and i1 %is_f4, %b1_f4_high",
            "  %special4 = or i1 %f0_case, %f4_case",
            "  %head_ok4 = or i1 %normal_case4, %special4",
            "  %ok4 = and i1 %head_ok4, %tails4",
            "  br i1 %ok4, label %four_advance, label %invalid",
            "one:",
            "  %next1 = add i64 %index, 1",
            "  br label %advance",
            "two_advance:",
            "  %next2 = add i64 %index, 2",
            "  br label %advance",
            "three_advance:",
            "  %next3 = add i64 %index, 3",
            "  br label %advance",
            "four_advance:",
            "  %next4 = add i64 %index, 4",
            "  br label %advance",
            "advance:",
            "  %next = phi i64 [ %next1, %one ], [ %next2, %two_advance ], [ %next3, %three_advance ], [ %next4, %four_advance ]",
            "  br label %loop",
            "valid:",
            "  ret i1 true",
            "invalid:",
            "  ret i1 false",
            "}",
        ])

    @staticmethod
    def _from_utf8() -> str:
        return "\n".join([
            "define private ptr @aether_string_from_utf8(ptr %bytes, i64 %length) {",
            "entry:",
            "  %negative = icmp slt i64 %length, 0",
            "  %null = icmp eq ptr %bytes, null",
            "  %nonempty = icmp ne i64 %length, 0",
            "  %bad_null = and i1 %null, %nonempty",
            "  %invalid_input = or i1 %negative, %bad_null",
            "  br i1 %invalid_input, label %utf8_panic, label %empty_check",
            "empty_check:",
            "  %empty = icmp eq i64 %length, 0",
            "  br i1 %empty, label %return_empty, label %validate",
            "return_empty:",
            "  ret ptr @.aether.string.empty",
            "validate:",
            "  %valid = call i1 @aether_string_is_valid_utf8(ptr %bytes, i64 %length)",
            "  br i1 %valid, label %size_payload, label %utf8_panic",
            "utf8_panic:",
            "  call void @aether_string_utf8_panic()",
            "  unreachable",
            "size_payload:",
            "  %payload_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %length, i64 1)",
            "  %payload = extractvalue { i64, i1 } %payload_pair, 0",
            "  %payload_overflow = extractvalue { i64, i1 } %payload_pair, 1",
            "  br i1 %payload_overflow, label %size_panic, label %size_total",
            "size_total:",
            "  %total_pair = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %payload, i64 24)",
            "  %total = extractvalue { i64, i1 } %total_pair, 0",
            "  %total_overflow = extractvalue { i64, i1 } %total_pair, 1",
            "  %total_too_large = icmp ugt i64 %total, 9223372036854775807",
            "  %bad_total = or i1 %total_overflow, %total_too_large",
            "  br i1 %bad_total, label %size_panic, label %allocate",
            "size_panic:",
            "  call void @aether_string_size_panic()",
            "  unreachable",
            "allocate:",
            "  %object = call noalias ptr @malloc(i64 %total)",
            "  %failed = icmp eq ptr %object, null",
            "  br i1 %failed, label %oom, label %initialize",
            "oom:",
            "  call void @aether_string_oom_panic()",
            "  unreachable",
            "initialize:",
            "  store i64 %length, ptr %object",
            "  %count_ptr = getelementptr i8, ptr %object, i64 8",
            "  store i64 1, ptr %count_ptr",
            "  %flags_ptr = getelementptr i8, ptr %object, i64 16",
            "  store i32 2, ptr %flags_ptr",
            "  %reserved_ptr = getelementptr i8, ptr %object, i64 20",
            "  store i32 0, ptr %reserved_ptr",
            "  %data = getelementptr i8, ptr %object, i64 24",
            "  call void @llvm.memcpy.p0.p0.i64(ptr %data, ptr %bytes, i64 %length, i1 false)",
            "  %terminator = getelementptr i8, ptr %data, i64 %length",
            "  store i8 0, ptr %terminator",
            "  ret ptr %object",
            "}",
        ])
