from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
import traceback
from typing import TextIO

from .errors import (
    AetherError,
    AetherRuntimeError,
    AetherSyntaxError,
    AetherTypeError,
    IRBackendUnsupportedFeatureError,
)


class DiagnosticCategory(str, Enum):
    SYNTAX = "syntax"
    TYPE = "type"
    CAPABILITY = "capability"
    RUNTIME = "runtime"
    TOOLCHAIN = "toolchain"
    INTERNAL_COMPILER_ERROR = "internal_compiler_error"


@dataclass(frozen=True)
class CompilerDiagnostic:
    category: DiagnosticCategory
    code: str
    message: str
    source_path: str | None = None
    line: int | None = None
    column: int | None = None
    note: str | None = None
    phase: str | None = None


EXIT_BY_CATEGORY = {
    DiagnosticCategory.SYNTAX: 1,
    DiagnosticCategory.TYPE: 1,
    DiagnosticCategory.CAPABILITY: 1,
    DiagnosticCategory.RUNTIME: 1,
    DiagnosticCategory.TOOLCHAIN: 3,
    DiagnosticCategory.INTERNAL_COMPILER_ERROR: 70,
}


def diagnostic_from_exception(
    exc: Exception,
    *,
    source_path: str | Path | None = None,
    phase: str | None = None,
) -> CompilerDiagnostic:
    """Translate an internal exception at a public compiler boundary."""

    chain = tuple(_exception_chain(exc))
    source = str(source_path) if source_path is not None else None

    # Verifier failures after accepted source always indicate compiler bugs.
    if _chain_has_name(chain, "IRVerificationError"):
        return _ice(
            "ICE-IR-VERIFY-001",
            "The compiler generated invalid IR",
            source,
            "IR verification",
        )
    if _chain_has_name(chain, "SSAVerificationError"):
        return _ice(
            "ICE-SSA-VERIFY-001",
            "The compiler generated invalid SSA",
            source,
            "SSA verification",
        )
    if _chain_has_name(chain, "ClangRejectedLLVMError"):
        return _ice(
            "ICE-LLVM-EMIT-001",
            "Clang rejected LLVM generated by the compiler",
            source,
            "LLVM validation",
        )
    if _chain_has_name(chain, "LLVMBackendError"):
        return _ice(
            "ICE-LLVM-EMIT-001",
            "The compiler could not emit structurally valid LLVM",
            source,
            "LLVM emission",
        )
    if _chain_has_name(chain, "GeneralSSABuildError", "SSARenameError"):
        return _ice(
            "ICE-SSA-BUILD-001",
            "The compiler could not construct SSA from valid IR",
            source,
            "SSA construction",
        )

    if _chain_has_name(chain, "ToolchainUnavailableError"):
        return CompilerDiagnostic(
            DiagnosticCategory.TOOLCHAIN,
            "TOOLCHAIN-CLANG-001",
            "Clang was not found. Install Clang and ensure it is available on PATH.",
            source_path=source,
            phase="native toolchain",
        )
    if _chain_has_name(
        chain,
        "ToolchainInvocationError",
        "LLVMBuildError",
        "LLVMRunError",
    ):
        return CompilerDiagnostic(
            DiagnosticCategory.TOOLCHAIN,
            "TOOLCHAIN-CLANG-001",
            _safe_toolchain_message(chain),
            source_path=source,
            phase="native toolchain",
        )

    from .capabilities import BackendCapabilityError

    if isinstance(exc, BackendCapabilityError):
        return CompilerDiagnostic(
            DiagnosticCategory.CAPABILITY,
            exc.kind or "AE-BACKEND-001",
            exc.format(),
            source_path=source,
            line=exc.line,
            column=exc.column,
            note=exc.hint,
            phase="capability checking",
        )
    if isinstance(exc, IRBackendUnsupportedFeatureError):
        return _from_aether_error(
            exc,
            DiagnosticCategory.CAPABILITY,
            "AE-BACKEND-IR-001",
            source,
            phase or "capability checking",
        )
    if isinstance(exc, AetherSyntaxError):
        return _from_aether_error(
            exc, DiagnosticCategory.SYNTAX, "AE-SYNTAX-001", source, "parsing"
        )
    if isinstance(exc, AetherTypeError):
        return _from_aether_error(
            exc, DiagnosticCategory.TYPE, "AE-TYPE-001", source, "type checking"
        )
    if isinstance(exc, AetherRuntimeError):
        return _from_aether_error(
            exc, DiagnosticCategory.RUNTIME, "AE-RUNTIME-001", source, phase or "runtime"
        )
    if isinstance(exc, AetherError):
        return _from_aether_error(
            exc, DiagnosticCategory.RUNTIME, "AE-RUNTIME-001", source, phase or "runtime"
        )

    ice_code = "ICE-OPT-001" if phase == "optimization" else "ICE-UNEXPECTED-001"
    return _ice(
        ice_code,
        "The compiler failed unexpectedly",
        source,
        phase or "compiler",
    )


def render_diagnostic(
    diagnostic: CompilerDiagnostic,
    *,
    stderr: TextIO,
    exception: Exception | None = None,
    debug: bool = False,
) -> None:
    category = diagnostic.category
    if category is DiagnosticCategory.INTERNAL_COMPILER_ERROR:
        print(f"Aether internal compiler error [{diagnostic.code}]", file=stderr)
        print(_message_with_source(diagnostic), file=stderr)
        if diagnostic.phase:
            print(f"Phase: {diagnostic.phase}", file=stderr)
        print("This is a compiler bug, not an error in your program.", file=stderr)
        if not debug:
            print("Run again with `--debug` to show internal details.", file=stderr)
    else:
        label = category.value.replace("_", " ")
        print(f"Aether {label} error [{diagnostic.code}]", file=stderr)
        print(diagnostic.message, file=stderr)
        location = _public_location(diagnostic)
        if location:
            print(location, file=stderr)

    if (
        debug
        and exception is not None
        and category is DiagnosticCategory.INTERNAL_COMPILER_ERROR
    ):
        print("", file=stderr)
        print("Internal details:", file=stderr)
        traceback.print_exception(exception, file=stderr)


def _from_aether_error(
    exc: AetherError,
    category: DiagnosticCategory,
    code: str,
    source: str | None,
    phase: str,
) -> CompilerDiagnostic:
    message = exc.format() if exc.has_details else f"{type(exc).__name__}: {exc.message}"
    return CompilerDiagnostic(
        category,
        code,
        message,
        source_path=source,
        line=exc.line,
        column=exc.column,
        note=exc.hint,
        phase=phase,
    )


def _ice(code: str, message: str, source: str | None, phase: str) -> CompilerDiagnostic:
    return CompilerDiagnostic(
        DiagnosticCategory.INTERNAL_COMPILER_ERROR,
        code,
        message,
        source_path=source,
        phase=phase,
    )


def _exception_chain(exc: BaseException):
    seen: set[int] = set()
    current: BaseException | None = exc
    while current is not None and id(current) not in seen:
        seen.add(id(current))
        yield current
        current = current.__cause__ or current.__context__


def _chain_has_name(chain: tuple[BaseException, ...], *names: str) -> bool:
    return any(type(item).__name__ in names for item in chain)


def _safe_toolchain_message(chain: tuple[BaseException, ...]) -> str:
    for item in chain:
        if type(item).__name__ == "ToolchainInvocationError":
            text = str(item).strip()
            if text:
                return text
    return "The native toolchain failed."


def _message_with_source(diagnostic: CompilerDiagnostic) -> str:
    if diagnostic.source_path:
        return f"{diagnostic.message} while compiling `{Path(diagnostic.source_path).name}`."
    return f"{diagnostic.message}."


def _public_location(diagnostic: CompilerDiagnostic) -> str | None:
    parts: list[str] = []
    if diagnostic.source_path:
        parts.append(Path(diagnostic.source_path).name)
    if diagnostic.line is not None:
        parts.append(f"line {diagnostic.line}")
    if diagnostic.column is not None:
        parts.append(f"column {diagnostic.column}")
    return "at " + ", ".join(parts) if parts else None
